Adding Changes made by @douggillespie to support old format of ctr files.
vmjanik/artwarp pull request #8
Opened 2021-11-18 05:55 UTC by RohanK22

These changes made by @douggillespie allow these older formats of ctr files to run. Here is the email discussing this issue: 
The ctr files @RohanK22 was testing with are from an old format. The data in them had the two variables fcontour and ostart, no freqContour. It seems the fcontour is now a built in Matlab function, which might explain a change from fcontour to freqContour. There is a bug whereby Matlab is getting very confused as to whether to use fcontour as the variable or as the function. Because fcontour does not appear as a variable name in the code, at the start of run time, the interpreter analyses the code, sees that there is no fcontour variable, and links to the function. fcontour is later created from the ctr file during the run, but it’s too late because the interpreter has already decided that it’s going to use the function, which of course fails. There is actually an easy work around – create a variable fcontour, then clear it at the top of the function, to trick the interpreter into assuming it’s a variable.

These changes were used to run ARTwarp successfully with the Killer Whale ctr files on OneDrive at "Steno Output/ARTwarp/Killer whale sample contours/".

2021-11-18 08:49 UTC, alex-konovalov requested changes
@RohanK22 this is a classical reading on how to write a good commit message: https://chris.beams.io/posts/git-commit/

As you can see at https://github.com/vmjanik/artwarp/pull/9/commits, your commit messages are written with a very long first line which is then truncated. It is recommended to have a short and informative line 1, then blank line and then a longer justification if necessary. That works nicely with tools to explore the history. 

We can fix your commit messages using interactive rebase - best to do that together in a call.

2021-11-19 10:28 UTC, alex-konovalov approved these changes

2021-11-19 10:31 UTC, alex-konovalov approved these changes
Looks good to me! We have refactored both #8 and #9 so if others are happy with the code, this can be merged (I'd recommend via "merge & rebase")

2021-11-19 16:57 UTC, alex-konovalov commented on ARTwarp_csv.m
> +addpath(pwd);
Same change as @tristankleyn did in #10. Would it make sense to check other files?

2022-01-21 10:19 UTC, alex-konovalov commented
Are we happy to merge this? I've invited @douggillespie @vmjanik @vdeecke as reviewers, would be nice to have a reply hear from at least one of you whether this looks good.

2022-02-03 15:15 UTC, douggillespie approved these changes

2022-02-03 15:53 UTC, merged